[package]
authors = ["nexovec"]
edition = "2018"
name = "lil_chess"
version = "0.1.0"

[dependencies]
tetra = "*"
sdl2 = "*"

# [features]
# sdl2_static_link = ["sdl2/static-link"]

[profile.release]
debug = 1

[rust]
debuginfo-level = 1
